spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/mydatabase
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8080