spring:
  datasource:
    url: jdbc:mysql://ustinterview.cbngx2f5jjah.ap-south-1.rds.amazonaws.com:3306/ustinterviews
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Finla2000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 5000